### ISSUE TITLE
blueimp-gallery.min.css 和 blueimp-gallery.css 内容不一致

### ISSUE THREAD

**Issue by dreamlx** [ken-wong/antsrepublic#2]
使用 blueimp-gallery.css slide 图片显示错误
blueimp-gallery.min.css 可以,但是需要替换 url => image-url

**Comment by ken-wong** [comment]
blueimp-gallery的css和js都删除了，用gem代替。
gem是[blueimp-gallery](https://github.com/Phifo/blueimp-gallery)
